# Generated by Django 2.0.7 on 2020-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=500)),
                ('cat', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('d_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='polls/images/')),
            ],
        ),
    ]
