# Generated by Django 2.0.7 on 2020-05-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='p_desc',
        ),
    ]
