# Generated by Django 2.0.7 on 2020-05-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200519_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
    ]
