# Generated by Django 2.0.7 on 2020-05-21 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_order_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2020, 5, 21)),
        ),
    ]
