# Generated by Django 2.0.7 on 2020-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200521_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
