# Generated by Django 2.0.7 on 2020-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200522_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='user_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
