# Generated by Django 2.0.7 on 2020-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_mail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
